### ISSUE TITLE
faiss T3 range search on SSNPP crash

### ISSUE THREAD

**Issue by gosha1128** [harsha-simhadri/big-ann-benchmarks#13]
@maumueller Alright, I tried the index strategy "OPQ32_128,IVF1048576_HNSW32,PQ32" on SSNPP and got the exception below.  Note that I'm now defaulting to CPU on build_index for this dataset since the quantizer class doesn't support range search.

I will next try to set quantizer_on_gpu_add=False and train_on_gpu=False for build_index().  The default was True for both.

----

...
Training PQ slice 30/32
Clustering 65536 points in 4D to 256 clusters, redo 1 times, 25 iterations
  Preprocessing in 0.00 s
  Iteration 24 (0.36 s, search 0.32 s): objective=1.11718e+07 imbalance=1.174 nsplit=0
Training PQ slice 31/32
Clustering 65536 points in 4D to 256 clusters, redo 1 times, 25 iterations
  Preprocessing in 0.00 s
  Iteration 24 (0.36 s, search 0.32 s): objective=1.12101e+07 imbalance=1.185 nsplit=0
doing polysemous training for PQ
IndexIVFPQ::precompute_table: not precomputing table, it would be too big: 34359738368 bytes (max 2147483648)
  Total train time 14384.034 s
============== SPLIT 0/1
Process Process-1:
Traceback (most recent call last):
  File "/home/george/anaconda3/envs/bigann/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/george/anaconda3/envs/bigann/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/george/Projects/BigANN/harsha/big-ann-benchmarks/benchmark/main.py", line 45, in run_worker
    run_no_docker(definition, args.dataset, args.count,
  File "/home/george/Projects/BigANN/harsha/big-ann-benchmarks/benchmark/runner.py", line 268, in run_no_docker
    run_from_cmdline(cmd)
  File "/home/george/Projects/BigANN/harsha/big-ann-benchmarks/benchmark/runner.py", line 182, in run_from_cmdline
    run(definition, args.dataset, args.count, args.runs, args.rebuild)
  File "/home/george/Projects/BigANN/harsha/big-ann-benchmarks/benchmark/runner.py", line 76, in run
    algo.fit(dataset)
  File "/home/george/Projects/BigANN/harsha/big-ann-benchmarks/benchmark/algorithms/faiss_t3.py", line 274, in fit
    index = build_index(buildthreads, by_residual, maxtrain,
  File "/home/george/Projects/BigANN/harsha/big-ann-benchmarks/benchmark/algorithms/faiss_t3.py", line 184, in build_index
    for xblock, assign in stage2:
  File "/home/george/Projects/BigANN/harsha/big-ann-benchmarks/benchmark/algorithms/faiss_t3.py", line 46, in rate_limited_iter
    res = res.get()
  File "/home/george/anaconda3/envs/bigann/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/home/george/anaconda3/envs/bigann/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/george/Projects/BigANN/harsha/big-ann-benchmarks/benchmark/algorithms/faiss_t3.py", line 39, in next_or_None
    return next(l)
  File "/home/george/Projects/BigANN/harsha/big-ann-benchmarks/benchmark/algorithms/faiss_t3.py", line 176, in produce_batches
    _, assign = quantizer_gpu.search(xblock, 1)
  File "/home/george/anaconda3/envs/bigann/lib/python3.8/site-packages/faiss/__init__.py", line 287, in replacement_search
    assert d == self.d
AssertionError

**Comment by mdouze** [comment]
range search is not supported in the T3 code yet.

**Comment by gosha1128** [comment]
ok thanks

**Comment by mdouze** [comment]
Ok, it is implemented now. Please use `--parallel_mode 2` to run SSNPP on GPU.

**Comment by gosha1128** [comment]
The new code is integrated into benchmark/algorithms/faiss_t3.py:

https://github.com/harsha-simhadri/big-ann-benchmarks/blob/gw/T3/benchmark/algorithms/faiss_t3.py

I tested it on ssnpp-10M.  Now doing 1B.
