### ISSUE TITLE
Cannot evaluate `python3 run.py --neurips23track filter --algorithm faiss --dataset yfcc-10M`

### ISSUE THREAD

**Issue by alexanderguzhva** [harsha-simhadri/big-ann-benchmarks#143]
```
> python3 run.py --neurips23track filter    --algorithm faiss   --dataset yfcc-10M
downloading https://dl.fbaipublicfiles.com/billion-scale-ann-benchmarks/yfcc100M/query.public.100K.u8bin -> data/yfcc100M/query.public.100K.u8bin...
  [2.55 s] downloaded 18.31 MiB / 18.31 MiB at 7.19 MiB/s   
download finished in 2.55 s, total size 19200008 bytes
downloading https://dl.fbaipublicfiles.com/billion-scale-ann-benchmarks/yfcc100M/GT.public.ibin -> data/yfcc100M/GT.public.ibin...
  [1.45 s] downloaded 7.63 MiB / 7.63 MiB at 5.28 MiB/s   
download finished in 1.45 s, total size 8000008 bytes
file data/yfcc100M/ already exists
file data/yfcc100M/ already exists
downloading https://dl.fbaipublicfiles.com/billion-scale-ann-benchmarks/yfcc100M/base.metadata.10M.spmat -> data/yfcc100M/base.metadata.10M.spmat...
  [94.03 s] downloaded 901.87 MiB / 901.87 MiB at 9.59 MiB/s   
download finished in 94.03 s, total size 945683840 bytes
downloading https://dl.fbaipublicfiles.com/billion-scale-ann-benchmarks/yfcc100M/query.metadata.public.100K.spmat -> data/yfcc100M/query.metadata.public.100K.spmat...
  [1.00 s] downloaded 1.82 MiB / 1.82 MiB at 1.82 MiB/s   
download finished in 1.00 s, total size 1907024 bytes
2023-07-18 19:55:12,243 - annb - INFO - running only faiss
2023-07-18 19:55:12,319 - annb - INFO - Order: [Definition(algorithm='faiss', constructor='FAISS', module='neurips23.filter.faiss.faiss', docker_tag='neurips23-filter-faiss', docker_volumes=[], arguments=['euclidean', {'indexkey': 'IVF16384,SQ8', 'binarysig': True, 'threads': 16}], query_argument_groups=[[{'nprobe': 1, 'mt_threshold': 0.0003}], [{'nprobe': 4, 'mt_threshold': 0.0003}], [{'nprobe': 16, 'mt_threshold': 0.0003}], [{'nprobe': 32, 'mt_threshold': 0.0003}], [{'nprobe': 64, 'mt_threshold': 0.0003}], [{'nprobe': 96, 'mt_threshold': 0.0003}], [{'nprobe': 1, 'mt_threshold': 0.0001}], [{'nprobe': 4, 'mt_threshold': 0.0001}], [{'nprobe': 16, 'mt_threshold': 0.0001}], [{'nprobe': 32, 'mt_threshold': 0.0001}], [{'nprobe': 64, 'mt_threshold': 0.0001}], [{'nprobe': 96, 'mt_threshold': 0.0001}], [{'nprobe': 1, 'mt_threshold': 0.01}], [{'nprobe': 4, 'mt_threshold': 0.01}], [{'nprobe': 16, 'mt_threshold': 0.01}], [{'nprobe': 32, 'mt_threshold': 0.01}], [{'nprobe': 64, 'mt_threshold': 0.01}], [{'nprobe': 96, 'mt_threshold': 0.01}]], disabled=False)]
RW Namespace(dataset='yfcc-10M', count=10, definitions='algos-2021.yaml', algorithm='faiss', docker_tag=None, list_algorithms=False, force=False, rebuild=False, runs=5, timeout=43200, max_n_algorithms=-1, power_capture='', t3=False, nodocker=False, upload_index=False, download_index=False, blob_prefix=None, sas_string=None, private_query=False, neurips23track='filter', runbook_path='neurips23/streaming/simple_runbook.yaml')
Setting container wait timeout to 30 minutes
2023-07-18 19:55:12,762 - annb.d25eedf2531c - INFO - Created container d25eedf2531c: CPU limit 0-11, mem limit 25092139776, timeout 1800, command ['--dataset', 'yfcc-10M', '--algorithm', 'faiss', '--module', 'neurips23.filter.faiss.faiss', '--constructor', 'FAISS', '--runs', '5', '--count', '10', '--neurips23track', 'filter', '["euclidean", {"indexkey": "IVF16384,SQ8", "binarysig": true, "threads": 16}]', '[{"nprobe": 1, "mt_threshold": 0.0003}]', '[{"nprobe": 4, "mt_threshold": 0.0003}]', '[{"nprobe": 16, "mt_threshold": 0.0003}]', '[{"nprobe": 32, "mt_threshold": 0.0003}]', '[{"nprobe": 64, "mt_threshold": 0.0003}]', '[{"nprobe": 96, "mt_threshold": 0.0003}]', '[{"nprobe": 1, "mt_threshold": 0.0001}]', '[{"nprobe": 4, "mt_threshold": 0.0001}]', '[{"nprobe": 16, "mt_threshold": 0.0001}]', '[{"nprobe": 32, "mt_threshold": 0.0001}]', '[{"nprobe": 64, "mt_threshold": 0.0001}]', '[{"nprobe": 96, "mt_threshold": 0.0001}]', '[{"nprobe": 1, "mt_threshold": 0.01}]', '[{"nprobe": 4, "mt_threshold": 0.01}]', '[{"nprobe": 16, "mt_threshold": 0.01}]', '[{"nprobe": 32, "mt_threshold": 0.01}]', '[{"nprobe": 64, "mt_threshold": 0.01}]', '[{"nprobe": 96, "mt_threshold": 0.01}]']
2023-07-18 19:55:13,268 - annb.d25eedf2531c - INFO - ['euclidean', {'indexkey': 'IVF16384,SQ8', 'binarysig': True, 'threads': 16}]
2023-07-18 19:55:13,268 - annb.d25eedf2531c - INFO - Trying to instantiate neurips23.filter.faiss.faiss.FAISS(['euclidean', {'indexkey': 'IVF16384,SQ8', 'binarysig': True, 'threads': 16}])
2023-07-18 19:55:13,305 - annb.d25eedf2531c - INFO - {'indexkey': 'IVF16384,SQ8', 'binarysig': True, 'threads': 16}
2023-07-18 19:55:13,305 - annb.d25eedf2531c - INFO - Running faiss on yfcc-10M
2023-07-18 19:55:13,305 - annb.d25eedf2531c - INFO - preparing binary signatures
2023-07-18 19:55:40,382 - annb.d25eedf2531c - INFO - writing to data/yfcc-10M.IVF16384,SQ8.binarysig
2023-07-18 19:55:44,039 - annb.d25eedf2531c - INFO - Traceback (most recent call last):
2023-07-18 19:55:44,039 - annb.d25eedf2531c - INFO -   File "/home/app/run_algorithm.py", line 3, in <module>
2023-07-18 19:55:44,039 - annb.d25eedf2531c - INFO -     run_from_cmdline()
2023-07-18 19:55:44,039 - annb.d25eedf2531c - INFO -   File "/home/app/benchmark/runner.py", line 222, in run_from_cmdline
2023-07-18 19:55:44,040 - annb.d25eedf2531c - INFO -     run(definition, args.dataset, args.count, args.runs, args.rebuild,
2023-07-18 19:55:44,040 - annb.d25eedf2531c - INFO -   File "/home/app/benchmark/runner.py", line 69, in run
2023-07-18 19:55:44,040 - annb.d25eedf2531c - INFO -     build_time = custom_runner.build(algo, dataset)
2023-07-18 19:55:44,040 - annb.d25eedf2531c - INFO -   File "/home/app/benchmark/algorithms/base_runner.py", line 7, in build
2023-07-18 19:55:44,040 - annb.d25eedf2531c - INFO -     algo.fit(dataset)
2023-07-18 19:55:44,040 - annb.d25eedf2531c - INFO -   File "/home/app/neurips23/filter/faiss/faiss.py", line 112, in fit
2023-07-18 19:55:44,040 - annb.d25eedf2531c - INFO -     xb = ds.get_dataset()
2023-07-18 19:55:44,040 - annb.d25eedf2531c - INFO -   File "/home/app/benchmark/datasets.py", line 217, in get_dataset
2023-07-18 19:55:44,040 - annb.d25eedf2531c - INFO -     slice = next(self.get_dataset_iterator(bs=self.nb))
2023-07-18 19:55:44,040 - annb.d25eedf2531c - INFO -   File "/home/app/benchmark/datasets.py", line 190, in get_dataset_iterator
2023-07-18 19:55:44,040 - annb.d25eedf2531c - INFO -     x = xbin_mmap(filename, dtype=self.dtype, maxn=self.nb)
2023-07-18 19:55:44,040 - annb.d25eedf2531c - INFO -   File "/home/app/benchmark/dataset_io.py", line 96, in xbin_mmap
2023-07-18 19:55:44,040 - annb.d25eedf2531c - INFO -     n, d = map(int, np.fromfile(fname, dtype="uint32", count=2))
2023-07-18 19:55:44,040 - annb.d25eedf2531c - INFO - FileNotFoundError: [Errno 2] No such file or directory: 'data/yfcc100M/base.10M.u8bin.crop_nb_10000000'
2023-07-18 19:55:44,390 - annb.d25eedf2531c - ERROR - ['euclidean', {'indexkey': 'IVF16384,SQ8', 'binarysig': True, 'threads': 16}]
Trying to instantiate neurips23.filter.faiss.faiss.FAISS(['euclidean', {'indexkey': 'IVF16384,SQ8', 'binarysig': True, 'threads': 16}])
{'indexkey': 'IVF16384,SQ8', 'binarysig': True, 'threads': 16}
Running faiss on yfcc-10M
preparing binary signatures
writing to data/yfcc-10M.IVF16384,SQ8.binarysig
Traceback (most recent call last):
  File "/home/app/run_algorithm.py", line 3, in <module>
    run_from_cmdline()
  File "/home/app/benchmark/runner.py", line 222, in run_from_cmdline
    run(definition, args.dataset, args.count, args.runs, args.rebuild,
  File "/home/app/benchmark/runner.py", line 69, in run
    build_time = custom_runner.build(algo, dataset)
  File "/home/app/benchmark/algorithms/base_runner.py", line 7, in build
    algo.fit(dataset)
  File "/home/app/neurips23/filter/faiss/faiss.py", line 112, in fit
    xb = ds.get_dataset()
  File "/home/app/benchmark/datasets.py", line 217, in get_dataset
    slice = next(self.get_dataset_iterator(bs=self.nb))
  File "/home/app/benchmark/datasets.py", line 190, in get_dataset_iterator
    x = xbin_mmap(filename, dtype=self.dtype, maxn=self.nb)
  File "/home/app/benchmark/dataset_io.py", line 96, in xbin_mmap
    n, d = map(int, np.fromfile(fname, dtype="uint32", count=2))
FileNotFoundError: [Errno 2] No such file or directory: 'data/yfcc100M/base.10M.u8bin.crop_nb_10000000'

2023-07-18 19:55:44,390 - annb.d25eedf2531c - ERROR - Child process for container d25eedf2531creturned exit code 1 with message None


```

**Comment by maumueller** [comment]
Thanks @alexanderguzhva, fixed in #144. 

For the time being, you can use `python create_dataset.py --dataset yfcc-10M` to download the base vectors.
