### ISSUE TITLE
TypeError: request() got an unexpected keyword argument 'chunked'

### ISSUE THREAD

**Issue by cheenyuee** [harsha-simhadri/big-ann-benchmarks#162]
when I use this command, there is an error.
```shell
python run.py --neurips23track ood       --algorithm diskann --dataset random-xs
``` 
how to fix this issue? Anybody can help me? thanks.

```shell
Preparing datasets with 10000 random points and 1000 queries.
Computing groundtruth
2023-09-04 21:25:39,786 - annb - INFO - running only diskann
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    main()
  File "/home/cy/work_cy/big-ann-benchmarks/benchmark/main.py", line 236, in main
    for image in docker_client.images.list():
  File "/home/cy/.local/lib/python3.8/site-packages/docker/models/images.py", line 230, in list
    resp = self.client.api.images(name=name, all=all, filters=filters)
  File "/home/cy/.local/lib/python3.8/site-packages/docker/api/image.py", line 93, in images
    res = self._result(self._get(self._url("/images/json"), params=params),
  File "/home/cy/.local/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/cy/.local/lib/python3.8/site-packages/docker/api/client.py", line 191, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/home/cy/.local/lib/python3.8/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/cy/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/cy/.local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/cy/.local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/cy/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/cy/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
TypeError: request() got an unexpected keyword argument 'chunked'
```

**Comment by maumueller** [comment]
Hi cheenyuee,

Could you please try to run it using Python 3.10? You can for example install https://docs.conda.io/projects/miniconda/en/latest/.
