### ISSUE TITLE
Timeout When Running Filter Baseline

### ISSUE THREAD

**Issue by sidjha1** [harsha-simhadri/big-ann-benchmarks#171]
Hello,

I followed the instructions in the README and ran `python run.py --neurips23track filter    --algorithm faiss   --dataset yfcc-10M` to generate the baselines for the filter track. However, the execution times out after 30 minutes. I'm attaching the tail of the log below for reference.
```
2023-10-01 18:10:21,322 - annb.56c11bb71c7a - INFO - running filtered query
2023-10-01 18:11:05,375 - annb.56c11bb71c7a - INFO - Running query argument group 12 of 18...
2023-10-01 18:11:05,375 - annb.56c11bb71c7a - INFO - Got 100000 queries
2023-10-01 18:11:05,375 - annb.56c11bb71c7a - INFO - Run 1/5...
2023-10-01 18:11:05,376 - annb.56c11bb71c7a - INFO - running filtered query
2023-10-01 18:11:53,919 - annb.56c11bb71c7a - INFO - Run 2/5...
2023-10-01 18:11:53,921 - annb.56c11bb71c7a - INFO - running filtered query
2023-10-01 18:12:40,962 - annb.56c11bb71c7a - ERROR - Container.wait for container 56c11bb71c7a failed with exception
2023-10-01 18:12:40,962 - annb.56c11bb71c7a - ERROR - Invoked with ['--dataset', 'yfcc-10M', '--algorithm', 'faiss', '--module', 'neurips23.filter.faiss.faiss', '--constructor', 'FAISS', '--runs', '5', '--count', '10', '--neurips23track', 'filter', '["euclidean", {"indexkey": "IVF16384,SQ8", "binarysig": true, "threads": 16}]', '[{"nprobe": 1, "mt_threshold": 0.0003}]', '[{"nprobe": 4, "mt_threshold": 0.0003}]', '[{"nprobe": 16, "mt_threshold": 0.0003}]', '[{"nprobe": 32, "mt_threshold": 0.0003}]', '[{"nprobe": 64, "mt_threshold": 0.0003}]', '[{"nprobe": 96, "mt_threshold": 0.0003}]', '[{"nprobe": 1, "mt_threshold": 0.0001}]', '[{"nprobe": 4, "mt_threshold": 0.0001}]', '[{"nprobe": 16, "mt_threshold": 0.0001}]', '[{"nprobe": 32, "mt_threshold": 0.0001}]', '[{"nprobe": 64, "mt_threshold": 0.0001}]', '[{"nprobe": 96, "mt_threshold": 0.0001}]', '[{"nprobe": 1, "mt_threshold": 0.01}]', '[{"nprobe": 4, "mt_threshold": 0.01}]', '[{"nprobe": 16, "mt_threshold": 0.01}]', '[{"nprobe": 32, "mt_threshold": 0.01}]', '[{"nprobe": 64, "mt_threshold": 0.01}]', '[{"nprobe": 96, "mt_threshold": 0.01}]']
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/neurips/lib/python3.10/site-packages/urllib3/response.py", line 710, in _error_catcher
    yield
  File "/home/ubuntu/miniconda3/envs/neurips/lib/python3.10/site-packages/urllib3/response.py", line 1073, in read_chunked
    self._update_chunk_length()
  File "/home/ubuntu/miniconda3/envs/neurips/lib/python3.10/site-packages/urllib3/response.py", line 1001, in _update_chunk_length
    line = self._fp.fp.readline()  # type: ignore[union-attr]
  File "/home/ubuntu/miniconda3/envs/neurips/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/neurips/lib/python3.10/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/home/ubuntu/miniconda3/envs/neurips/lib/python3.10/site-packages/urllib3/response.py", line 933, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "/home/ubuntu/miniconda3/envs/neurips/lib/python3.10/site-packages/urllib3/response.py", line 1061, in read_chunked
    with self._error_catcher():
  File "/home/ubuntu/miniconda3/envs/neurips/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ubuntu/miniconda3/envs/neurips/lib/python3.10/site-packages/urllib3/response.py", line 715, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.") from e  # type: ignore[arg-type]
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/big-ann-benchmarks/benchmark/runner.py", line 318, in run_docker
    return_value = container.wait(timeout=timeout)
  File "/home/ubuntu/miniconda3/envs/neurips/lib/python3.10/site-packages/docker/models/containers.py", line 514, in wait
    return self.client.api.wait(self.id, **kwargs)
  File "/home/ubuntu/miniconda3/envs/neurips/lib/python3.10/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/neurips/lib/python3.10/site-packages/docker/api/container.py", line 1338, in wait
    res = self._post(url, timeout=timeout, params=params)
  File "/home/ubuntu/miniconda3/envs/neurips/lib/python3.10/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/neurips/lib/python3.10/site-packages/docker/api/client.py", line 233, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/home/ubuntu/miniconda3/envs/neurips/lib/python3.10/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/ubuntu/miniconda3/envs/neurips/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/miniconda3/envs/neurips/lib/python3.10/site-packages/requests/sessions.py", line 747, in send
    r.content
  File "/home/ubuntu/miniconda3/envs/neurips/lib/python3.10/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/home/ubuntu/miniconda3/envs/neurips/lib/python3.10/site-packages/requests/models.py", line 822, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.
```
I found that the 30 minute timeout is being set in these lines of code
https://github.com/harsha-simhadri/big-ann-benchmarks/blob/31559521f64fdacc3088d47b7ea362a0edbd7f1d/benchmark/runner.py#L292-L294
Is the run supposed to finish in 30 minutes? I'm using a machine similar to Azure Standard D8lds v5.

**Comment by maumueller** [comment]
Thanks for the observation @sidjha1 

@harsha-simhadri Isn't this particular timeout only for the streaming case?

**Comment by maumueller** [comment]
@sidjha1 @harsha-simhadri already addressed this in https://github.com/harsha-simhadri/big-ann-benchmarks/pull/170/, so I'm closing this.
