### ISSUE TITLE
track1_baseline_faiss/baseline_faiss.py runs out of memory for 100M vectors on F32s_v2 with 64G RAM

### ISSUE THREAD

**Issue by DmitryKey** [harsha-simhadri/big-ann-benchmarks#21]
Hello!

Thanks for providing the scripts for running baselines. The following one liner:

```
python -u track1_baseline_faiss/baseline_faiss.py --dataset bigann-100M \
    --indexkey OPQ64_128,IVF1048576_HNSW32,PQ64x4fsr \
    --maxtrain 100000000 \
    --two_level_clustering \
    --build \
    --add_splits 30 \
    --indexfile data/track1_baseline_faiss/deep-100M.IVF1M_2level_PQ64x4fsr.faissindex \
    --quantizer_efConstruction 200 \
    --quantizer_add_efSearch 80
```

produces output on F32s_v2 with 64G RAM:

```
args= Namespace(M0=-1, add_bs=100000, add_splits=30, autotune_max=[], autotune_range=[], basedir=None, build=True, buildthreads=-1, by_residual=-1, clustering_niter=-1, dataset='bigann-100M', indexfile='data/track1_baseline_faiss/deep-100M.IVF1M_2level_PQ64x4fsr.faissindex', indexkey='OPQ64_128,IVF1048576_HNSW32,PQ64x4fsr', inter=True, k=10, maxRAM=-1, maxtrain=100000000, min_test_duration=3.0, n_autotune=500, no_precomputed_tables=False, pairwise_quantization='', parallel_mode=-1, prepare=False, quantizer_add_efSearch=80, quantizer_efConstruction=200, query_bs=-1, radius=96237, search=False, searchparams=['autotune'], searchthreads=-1, stop_at_split=-1, train_on_gpu=False, two_level_clustering=True)
nb processors 32
model name	: Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
Dataset BigANNDataset in dimension 128, with distance euclidean, search_type knn, size: Q 10000 B 100000000
build index, key= OPQ64_128,IVF1048576_HNSW32,PQ64x4fsr
Build-time number of threads: 32
metric type 1
Update add-time parameters
   update quantizer efSearch= 16 -> 80
  update quantizer efConstruction= 40 -> 200
getting first 100000000 dataset vectors for training
train, size (100000000, 128)
  Forcing OPQ training PQ to PQ4
  training vector transform
  transform trainset
Killed
```

Can you please explain what could be wrong? Is the expectation to allocate 10% of data for training?

**Comment by DmitryKey** [comment]
Ok, after changing `--maxtrain` to 10M (10% of 100M) it began to index. Just wanted to make sure this is the expected setting?

**Comment by DmitryKey** [comment]
Indexing has completed, but it could not write to disk:
```
  IndexIVFPQFastScan::add_with_ids 0: 65536   IndexIVFPQFastScan::add_with_ids 65536: 100000  adding 99966666:100000000 / 100000000 [3400.285 s, RSS 18204608 kiB] 
  add in 3401.458 s
storing data/track1_baseline_faiss/deep-100M.IVF1M_2level_PQ64x4fsr.faissindex
Traceback (most recent call last):
  File "track1_baseline_faiss/baseline_faiss.py", line 791, in <module>
    main()
  File "track1_baseline_faiss/baseline_faiss.py", line 742, in main
    index = build_index(args, ds)
  File "track1_baseline_faiss/baseline_faiss.py", line 246, in build_index
    faiss.write_index(index, args.indexfile)
  File "/datadrive/anaconda3/envs/faiss_1.7.1/lib/python3.8/site-packages/faiss/swigfaiss_avx2.py", line 5418, in write_index
    return _swigfaiss_avx2.write_index(*args)
RuntimeError: Error in faiss::FileIOWriter::FileIOWriter(const char*) at /opt/conda/conda-bld/faiss-pkg_1623024438023/work/faiss/impl/io.cpp:98: Error: 'f' failed: could not open data/track1_baseline_faiss/deep-100M.IVF1M_2level_PQ64x4fsr.faissindex for writing: No such file or directory
```

**Comment by harsha-simhadri** [comment]
Index build for T1 would be on a machine with 128GB RAM and an additional 4TB disk attached. You can assume you can access the disk with a symbolic link to data. Are you able to try it on the larger spec VM?

**Comment by DmitryKey** [comment]
hey @harsha-simhadri thanks for clarifying the VM spec -- I will take a look, just need to spin a few plates on my own algorithm before that. Thanks!

**Comment by DmitryKey** [comment]
Hi @harsha-simhadri on the website it says:

Track 1: In-memory indices with FAISS as the baseline. Search would use Azure Standard_F32s_v2 VMs with 32 vCPUs and 64GB RAM. Index construction would use Azure Standard_F64s_v2 VM with 64vCPUs, 128GB RAM and an additional 4TB of SSD to be used for storing the data, index and other intermediate data.


So I have read it as: for search I will be using a 64GB RAM VM, but I have misinterpreted the indexing side. So all clear, I will close this ticket. Thanks for your help!
